# Generated by Django 6.0.3 on 2026-03-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grades', models.IntegerField()),
                ('interest', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.TextField(blank=True)),
                ('traits', models.TextField(blank=True)),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
